---
- name: Deploy ihat
  tags: ['rails_deploy']
  hosts: all
  sudo: true
  vars:
    env:
      REDIS_URL: "{{ redis_url }}"
      SECRET_KEY_BASE: "{{ rails_secret_key_base }}"

  pre_tasks:
    - name: "Change permissions for application source"
      tags: 'ihat-staging'
      file: path={{ rails_deploy_src }}
            state=directory
            owner={{ rails_deploy_service }}
            recurse="yes"
    - name: Clone meTypeset repo
      git: repo=https://github.com/MartinPaulEve/meTypeset.git
           dest=/home/{{ rails_deploy_service }}/meTypeset
    - name: Source app defaults file from /etc/profile
      lineinfile: dest=/etc/profile 
                  line='. /etc/default/'{{ rails_deploy_service }}
  post_tasks:
    - name: Add TEI package source
      apt_repository: repo='deb http://tei.oucs.ox.ac.uk/teideb/binary ./' state=present
    - name: Add TEI apt key
      apt_key: keyserver=wwwkeys.uk.pgp.net id=FEA4973F86A9A497
    - name: Install OxGarage from TEI repo
      apt: name=tei-oxgarage update_cache=yes state=latest
    - name: Restart app services
      service: name={{ item }} state=restarted
      with_items:
        - "{{ rails_deploy_service }}"
        - "{{ rails_deploy_worker }}"
    - name: Wait for app to start
      wait_for: port='{{item}}' delay='5' timeout='600'
      with_items: 
        - '443'


  roles:
    - { role: joshualund.ruby-2_1, tags: ['ruby'] }
    - { role: debops.pki, tags: ['debops'], sudo: true }
    - { role: debops.rails_deploy, tags: ['rails_deploy'], sudo: true }
